modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="jpomc"
version="1.0.0"
displayName="JPOMC"
credits="JPOMCdev"
displayURL="https://jpomc.fr"
logoFile="logo.png"
authors="JPOMCdev"

[[dependencies.jpomc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




